In [1]:
import pandas as pd

In [4]:
cat_df = pd.read_csv('./categories.csv')
course_df = pd.read_csv('./courses.csv')

In [6]:
cat_df['category']

0          Computer Science
1            Math and Logic
2                  Business
3      Personal Development
4         Language Learning
5    Information Technology
Name: category, dtype: object

In [24]:
total_courses = len(course_df['course_id'])
sim_C = {'course_id': [i for i in range(total_courses)]}
for i in range(total_courses):
    sim_C[i] = []
    for j in range(total_courses):
        cat1 = course_df[course_df['course_id'] == i].category.values[0]
        cat2 = course_df[course_df['course_id'] == j].category.values[0]
        sim_C[i].append(cat_df[cat_df['category'] == cat1][cat2].values[0])

In [26]:
new_df = pd.DataFrame(sim_C)
new_df.head()

,course_id,0,1,2,3,4,5,6,7,8,...,10,11,12,13,14,15,16,17,18,19
0,0,1.0,0.5,1.0,0.2,0.5,0.2,0.2,0.1,0.1,...,0.2,0.2,0.8,0.2,0.8,0.2,0.1,0.8,0.8,1.0
1,1,0.5,1.0,0.5,0.1,1.0,0.1,0.1,0.1,0.1,...,0.1,0.1,0.5,0.1,0.5,0.1,0.1,0.5,0.5,0.5
2,2,1.0,0.5,1.0,0.2,0.5,0.2,0.2,0.1,0.1,...,0.2,0.2,0.8,0.2,0.8,0.2,0.1,0.8,0.8,1.0
3,3,0.2,0.1,0.2,1.0,0.1,0.8,0.8,0.4,0.4,...,0.8,1.0,0.1,1.0,0.1,1.0,0.4,0.1,0.1,0.2
4,4,0.5,1.0,0.5,0.1,1.0,0.1,0.1,0.1,0.1,...,0.1,0.1,0.5,0.1,0.5,0.1,0.1,0.5,0.5,0.5

In [28]:
new_df.to_csv('./simC_matrix.csv', index=False)